### Register need different username and email
POST localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "testUser10",
  "password": "123456",
  "email": "10@gmail.com"
}

### Login
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "testUser",
  "password": "123456"
}

### Refresh token
POST localhost:8080/api/auth/refresh
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Y2U0ZWE5ZGY1MWFiYjA5YmY1M2E1MiIsImFkbWluIjp0cnVlLCJpYXQiOjE2OTEyNjMwMDgsImV4cCI6MTY5MTI2MzMwOH0.dzO9bIt4osv49EONVPpMh5XSjznHYGt9N9aFJVPYz2c

### Logout (token verify)
POST localhost:8080/api/auth/logout
Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Y2U0ZWE5ZGY1MWFiYjA5YmY1M2E1MiIsImFkbWluIjp0cnVlLCJpYXQiOjE2OTEyNjIyMDEsImV4cCI6MTY5MTI2MjIyMX0.CJqZNuD3JOoK5wVlP1Qd_U644FSD6CNlsCTU7r9vxDA

### Get all users (admin)
GET localhost:8080/api/admin/users
Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjkxMjYzMDMxLCJleHAiOjE2OTEyNjMwNTF9.YJT8fyawBADr8E6auB4IfE4FebtWdrbSsac3rTsbZQA


### Delete user (admin)
DELETE localhost:8080/api/admin/users/64ce1ec1259987e73646901c
